### PR TITLE
feat: add supportModelType, gpt-4o, gpt4o-2024-05-13

### PR DESCRIPTION
**Pull request by kingchan818**

### CODE REVIEW

**Comment by Cainier** [comment]
Thank you for maintaining this project

**Comment by hellohejinyu** [comment]
## gpt-4o still doesn't work

image

## gpt-4o support new format content with image, Is billing valid for the new format of content?

image

## even if I use ts-ignore to ignore the error, the console still prompts model not found

image

**Comment by kingchan818** [comment]
@hellohejinyu, the commit is pending to review in https://github.com/Cainier/gpt-tokens/pull/48 now, as I forgot to define gpt4o type.

**Comment by Cainier** [comment]
OK, I merged the relevant commits and moved the type `supportModelType` to `pricing.ts`

The fixed version is v1.3.6

**Pull request merged**
